import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "@/compoinents/wrapper/wrapper";
import { FavoritesProvider } from "@/context/favorites-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FavoritesProvider>
        <body className={inter.className}>
          <Wrapper>{children}</Wrapper>
        </body>
      </FavoritesProvider>
    </html>
  );
}
